### ISSUE TITLE
pip install failing on finding tensorflow=2.7.0

### ISSUE THREAD

**Issue by maykcaldas** [Iagea/DECIMER-Image-Classifier#4]
Hello!
Thanks for Decimer. Really interesting project!!

I tried to import it as suggested in the README file:

```pip install git+https://github.com/Iagea/DECIMER-Image-Classifier```

but it uses a specific version of tensorflow that colab isn't able to find. It raises this error:

```
INFO: pip is looking at multiple versions of decimer-image-classifier to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from decimer-image-classifier) (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0)
ERROR: No matching distribution found for tensorflow==2.7.0
```

Is there a workaround for that?

Thanks!
Mayk

EDIT: It apparently works fine with TF 2.13.0

**Comment by Kohulan** [comment]
@maykcaldas,

Thanks for letting us know. It is usually the case that a higher Python version might not support TF 2.7.0. I suggest you use TF 2.12.0, which currently passed all our tests.

- Kohulan
